### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by vitoTTW** [SeveNOlogy7/SimMoLFil#2]
I think the NLSE equation in reference you cite is wrong. And，there are some problems with the expression and calculation of the dispersion coefficient.

**Comment by SeveNOlogy7** [comment]
@vitoTTW 
> I think the NLSE equation in reference you cite is wrong.

Many thanks for pointing this out. Yes, the loss and dispersion terms of the NLSE equation in this [reference](https://www.osapublishing.org/oe/abstract.cfm?uri=oe-25-4-4414) appear to have wrong signs.

> And，there are some problems with the expression and calculation of the dispersion coefficient.

Except for the signs, the expansion of the dispersion term looks correct to me. In terms of calculation, please could you specify where in the codes you think that may be wrong?
