### ISSUE TITLE
Question in initial rand signal

### ISSUE THREAD

**Issue by liu-bowen** [SeveNOlogy7/SimMoLFil#3]
It seems that the initial signal in "rand_sech" subfunction is not a random pulse. Two inputs "nt" and "time" are given in the main function, and the other two of "beta2" and "gamma" are defined as constants in your codes, if they are not declared in main function. I see the random number generator "rng(0)" is set up, while it isn't used to define any variables of "u0" and thus no random factor is introduced, which makes me confused.

**Comment by SeveNOlogy7** [comment]
@liu-bowen
[Here](https://github.com/SeveNOlogy7/SimMoLFil/blob/master/SimMolFil/Ultility/rand_sech.m), the following codes generate random noise signal with a sech envelope:
```
u0 =sqrt(P_peak)*sech(t/tfwhm); 
rng(0);
u0 = abs(wgn(nt,1,25))'.*u0;
```
`u0` is firstly assigned with a sech profile.
`wgn` function generates white gaussian noise signal 
So `u0 = abs(wgn(nt,1,25))'.*u0` applys the sech envelope to the noise.

**Comment by liu-bowen** [comment]
Thank you for your explanation. I can understand the codes, though I used to work on python so matlab is new for me.
I think is the wgn function confused me, because in guidebook matlab doesn't say it's a random item.
Forgive me, but may I ask why you decide the power value of wgn as 25 dBW. As you know it's a very big number.

**Comment by SeveNOlogy7** [comment]
@liu-bowen
You're very welcome.

The power value of `wgn` is currently the only straightforward parameter to set the pulse energy of the initial random signal for the simulation, and it's hidden in the code. You reminded me that maybe I should provide an easier interface to set up the random signal.

Back to your question, the power or pulse energy of the initial signal is determined by the sech profile and the 'wgn' function. Indeed, you can estimate the energy of the signal 'u0' directly, if you could run [this example](https://github.com/SeveNOlogy7/SimMoLFil/blob/master/Examples/mainP1.m), you shall see output at the beginning of the execution like this:
```
Input Peak Power (W) = 77.60
Input Pulse Energy in pJ = 444.83
```
The values may change but should be roughly in this magnitude. 

I used this programme myself to simulate high-energy dissipative soliton, typically with pulse energy >100 nJ, so you see this initial seed is not that powerful.

In most stable cases, the initial seeds for the simulation do not affect the results, look for the term 'attractor' in the mode-lock simulation field if you're interested. But, their energy affects the convergence speed, which is a parameter you should try yourself to find the optimal.
